---
- hosts: all
  vars_files: vars.yml

  tasks:

    - name: Ensure group “deploy” exists
      become: true
      group:
        name: deploy
        state: present

    - name: Add the user ‘{{ host_user }}’ with a specific uid and a primary group of ‘admin’
      become: true
      shell: adduser ubuntu deploy

    - name: recursively change owership of a directory
      become: true
      shell: chown -R ubuntu:deploy /srv

    - name: Change file ownership, group and permissions
      become: true
      shell: chmod 2775 "{{ project_root_dir }}"

    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
      become: true
      shell: find {{ project_root_dir }} -type d -exec chmod 2775 {} +

    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
      become: true
      shell: find {{ project_root_dir }} -type f -exec chmod 0664 {} +


##################Install Docker & Required dependencies ################################

    
 
    - name: install required dependencies
      become: true
      apt: pkg={{ item }} state=latest
      with_items: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker s official GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker  

    - name: Verify that we have the key with the fingerprint
      become: true
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker


    - name: Set up the stable repository
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Update apt packages
      become: true
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install docker
      become: true
      apt:
        name: docker-ce
        state: present
        update_cache: yes
    #notify: Start docker on boot
      tags:
        - docker

    - name: Add remote "ubuntu" user to "docker" group
      become: true
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Install docker-compose
      become: true
      get_url: 
        url : https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'


###--------------------------------------------------------------------------------------------------------------------------

    #pull the repo
    - name: Add github to known hosts
      shell: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Transfer Repo Key
      template:
        src: ./id_rsa
        dest: ~/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Get stuff from git
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "{{ api_project_dir }}"
        version: "{{ repo_branch }}"
        accept_hostkey: yes
        update: yes
        force: yes
    #################Spin the container#####################

  
    - name: Spin the container
      become: yes
      shell: docker-compose up -d
      ignore_errors: yes
      args:
        chdir: "{{ api_project_dir }}"

